### ISSUE TITLE
Failed to load PCB with tildes in a net name

### ISSUE THREAD

**Issue by cyrozap** [theacodes/kicanvas#32]
[This file](https://github.com/cyrozap/HDMI-to-MIPI/blob/master/HDMI-to-LH550WF1/HDMI-to-LH550WF1.kicad_pcb) failed to load with the following error:

```
<kicanvas-app>  @ 14.327s
kicanvas.js:937  Loading project from GitHubFileSystem  @ 14.327s
kicanvas.js:937  Loading file HDMI-to-LH550WF1.kicad_pcb  @ 14.327s
kicanvas.js:937  Parsing expression with 594380 chars  @ 14.694s
kicanvas.js:1619 Error: Unexpected character while tokenizing atom at index 3637: ~
Context: 
  (net 61 /Control/~TRST~)
    at tokenize (kicanvas.js:941:144)
    at BV.next (<anonymous>)
    at listify_tokens (kicanvas.js:946:82)
    at vl.next (<anonymous>)
    at Function.from (<anonymous>)
    at listify_tokens (kicanvas.js:946:192)
    at vl.next (<anonymous>)
    at Function.from (<anonymous>)
    at listify_tokens (kicanvas.js:946:192)
    at vl.next (<anonymous>)
setup_project @ kicanvas.js:1619
await in setup_project (async)
(anonymous) @ kicanvas.js:1619
kicanvas.js:937  Completed  @ 14.697s
```

**Comment by theacodes** [comment]
Hi, this file is from KiCAD 4 and can't be loaded in KiCanvas. Issue #34 tracks notifying users for incompatible files.
