### ISSUE TITLE
No error message + didn't load GH repo

### ISSUE THREAD

**Issue by LucianoHanna** [theacodes/kicanvas#57]
I tried to load this github repo https://github.com/dilshan/12v-automatic-ups but nothing happen.

Maybe this GH repo have something broken or incompatible with kicanvas but should show an error message. I didn't know there was an error until I opened DevTools

DevTools console output:
```
kicanvas.js:971 GET https://api.github.com/repos/dilshan/12v-automatic-up/contents/?ref=HEAD 404 (Not Found)
request @ kicanvas.js:971
repos_contents @ kicanvas.js:971
fromURLs @ kicanvas.js:971
(anonymous) @ kicanvas.js:1783


kicanvas.js:971 Uncaught (in promise) NotFoundError: GitHubNotFoundError: https://api.github.com/repos/dilshan/12v-automatic-up/contents/?ref=HEAD: not found
    at s.handle_server_error (kicanvas.js:971:10375)
    at s.request (kicanvas.js:971:10077)
    at async s.repos_contents (kicanvas.js:971:10475)
    at async GitHubFileSystem.fromURLs (kicanvas.js:971:11702)
    at async HTMLInputElement.<anonymous> (kicanvas.js:1783:653)
handle_server_error @ kicanvas.js:971
request @ kicanvas.js:971


kicanvas.js:926 kicanvas:project: Loading project from GitHubFileSystem

kicanvas.js:926 kicanvas:project: Determining schematic hierarchy


kicanvas.js:1783 Error: Unable to find undefined
    at Wt.set_active_page (kicanvas.js:971:8453)
    at tt.setup_project (kicanvas.js:1783:905)
    at async HTMLInputElement.<anonymous> (kicanvas.js:1783:674)
setup_project @ kicanvas.js:1783
await in setup_project (async)
(anonymous) @ kicanvas.js:1783```

**Comment by XiangYyang** [comment]
Thank you so much for letting me know! Check out #124 for more information. In short, the reason for this issue is that subdirectories are not being scanned. A possible fix for #119 requires scanning subdirectories, which will resolve this issue, partially. 

But, I'm sorry to have to tell you this, I have to tell you that this repository contains older versions of KiCad 5 files. Unfortunately, these are currently unsupported by KiCanvas, see #34. I know it's really frustrating. This issue cannot be easily resolved.
